// ✅ A curated list of medical terms or symptom keywords
// You can expand this list based on your chatbot's training data

module.exports = [
  "fever",
  "cough",
  "cold",
  "headache",
  "migraine",
  "asthma",
  "hypertension",
  "diabetes",
  "chest pain",
  "allergy",
  "fatigue",
  "nausea",
  "vomiting",
  "dizziness",
  "sore throat",
  "stomach ache",
  "back pain",
  "anxiety",
  "depression",
  "skin rash",
  "infection",
  "injury",
  "fracture",
  "bleeding",
  "shortness of breath",
  "joint pain",
  "swelling",
  "burns",
  "diarrhea",
  "constipation",
  "palpitations",
  "insomnia",
  "ear pain",
  "eye redness",
  "vision problems",
  "weight loss",
  "weight gain",
  "pregnancy",
  "child fever",
  "elderly fall"
];
